### ISSUE TITLE
 Failed to read accessWidener file from mod fabric-content-registries-v0

### ISSUE THREAD

**Issue by Sneakometer** [FabricMC/access-widener#18]
Hey there,

I updated my fabric gradle project from 1.17 to 1.18-rc-4, featuring fabric 0.43.1+1.18, fabric-loom 0.10-SNAPSHOT, fabric-loader 0.12.5 and Java 17.
Building works just fine, but trying to run the client with `gradlew runClient` runs into the following problem:
```java
> Configure project :
Fabric Loom: 0.10.62

> Task :runClient FAILED
[09:32:13] [main/INFO] (FabricLoader/GameProvider) Loading for game Minecraft 1.18-rc4
[09:32:14] [main/INFO] (FabricLoader) Loading 50 mods:
        - elytrakey 1.1.0
        - fabric 0.43.1+1.18
        - fabric-api-base 0.4.1+b4f4f6cd14
        - fabric-api-lookup-api-v1 1.3.5+3ac43d9514
        - fabric-biome-api-v1 6.0.1+3ac43d9514
        - fabric-blockrenderlayer-v1 1.1.9+3ac43d9514
        - fabric-command-api-v1 1.1.6+3ac43d9514
        - fabric-commands-v0 0.2.5+b4f4f6cd14
        - fabric-containers-v0 0.1.18+d154e2c614
        - fabric-content-registries-v0 0.4.5+6f53a73d14
        - fabric-crash-report-info-v1 0.1.8+3ac43d9514
        - fabric-dimensions-v1 2.1.7+43d2957114
        - fabric-entity-events-v1 1.4.5+6b21378a14
        - fabric-events-interaction-v0 0.4.15+3ac43d9514
        - fabric-events-lifecycle-v0 0.2.5+b4f4f6cd14
        - fabric-game-rule-api-v1 1.0.10+3ac43d9514
        - fabric-gametest-api-v1 1.0.5+03d159cf14
        - fabric-item-api-v1 1.2.7+3ac43d9514
        - fabric-item-groups-v0 0.3.3+3ac43d9514
        - fabric-key-binding-api-v1 1.0.8+c8aba2f314
        - fabric-keybindings-v0 0.2.6+b4f4f6cd14
        - fabric-lifecycle-events-v1 1.4.10+c15ca33514
        - fabric-loot-tables-v1 1.0.8+3ac43d9514
        - fabric-mining-level-api-v1 1.0.3+3ac43d9514
        - fabric-mining-levels-v0 0.1.7+b4f4f6cd14
        - fabric-models-v0 0.3.3+3ac43d9514
        - fabric-networking-api-v1 1.0.18+3ac43d9514
        - fabric-networking-v0 0.3.5+b4f4f6cd14
        - fabric-object-builder-api-v1 1.10.13+3ac43d9514
        - fabric-object-builders-v0 0.7.7+3ac43d9514
        - fabric-particles-v1 0.2.9+526dc1ac14
        - fabric-registry-sync-v0 0.8.5+3ac43d9514
        - fabric-renderer-api-v1 0.4.9+3ac43d9514
        - fabric-renderer-indigo 0.4.12+3ac43d9514
        - fabric-renderer-registries-v1 3.2.7+b4f4f6cd14
        - fabric-rendering-data-attachment-v1 0.3.3+d154e2c614
        - fabric-rendering-fluids-v1 0.1.18+3ac43d9514
        - fabric-rendering-v0 1.1.9+b4f4f6cd14
        - fabric-rendering-v1 1.10.3+6b21378a14
        - fabric-resource-loader-v0 0.4.11+3ac43d9514
        - fabric-screen-api-v1 1.0.7+3ac43d9514
        - fabric-screen-handler-api-v1 1.1.11+3ac43d9514
        - fabric-structure-api-v1 2.0.8+295197a714
        - fabric-tag-extensions-v0 1.2.5+3ac43d9514
        - fabric-textures-v0 1.0.9+3ac43d9514
        - fabric-tool-attribute-api-v1 1.3.4+7de09f5514
        - fabric-transfer-api-v1 1.5.4+b4f4f6cd14
        - fabricloader 0.12.5
        - java 17
        - minecraft 1.18-rc.4
Exception in thread "main" java.lang.RuntimeException: Failed to read accessWidener file from mod fabric-content-registries-v0
        at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:451)
        at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:122)
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
        at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
        at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
Caused by: net.fabricmc.accesswidener.AccessWidenerFormatException: line 1: Namespace (intermediary) does not match current runtime namespace (named)
        at net.fabricmc.accesswidener.AccessWidenerReader.error(AccessWidenerReader.java:281)
        at net.fabricmc.accesswidener.AccessWidenerReader.read(AccessWidenerReader.java:90)
        at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:449)
        ... 4 more

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':runClient'.
> Process 'command 'C:\Program Files\Java\jdk-17.0.1+12\bin\java.exe'' finished with non-zero exit value 1
```

How can i fix that? I need help.
Thank you!

**Comment by modmuss50** [comment]
This was fixed, refreshing gradle should solve the issue.
